### ISSUE TITLE
Mattermost client not starting anymore

### ISSUE THREAD

**Issue by socialSynergy** [Kopano-dev/mattermost-plugin-kopanowebmeetings#12]
Mattermost (v5.13.2) doesn't start anymore after plugin activation.

**Server log:**
At the beginning:
`{"level":"info","ts":1576092056.4354622,"caller":"go-plugin/stream.go:15","msg":"OnActivate kwmmmserverd","plugin_id":"kopanowebmeetings","source":"plugin_stdout"}`

After a few moments:
```
"{"level":"info","ts":1576092583.047923,"caller":"go-plugin/stream.go:15","msg":"2019/12/11 19:29:43 kwm plugin error *errors.errorString while getting client configration: unexpected HTTP response: 404","plugin_id":"kopanowebmeetings","source":"plugin_stderr"}
{"level":"info","ts":1576092590.4738464,"caller":"go-plugin/stream.go:15","msg":"2019/12/11 19:29:50 kwm plugin error *errors.errorString while getting client configration: unexpected HTTP response: 404","plugin_id":"kopanowebmeetings","source":"plugin_stderr"}
{"level":"info","ts":1576092592.903127,"caller":"go-plugin/stream.go:15","msg":"2019/12/11 19:29:52 kwm plugin error *errors.errorString while getting client configration: unexpected HTTP response: 404","plugin_id":"kopanowebmeetings","source":"plugin_stderr"}
```

**Client (browser) side:**

Failed to load resource: the server responded with a status of 500 (Internal Server Error)

--> https://domain.com/plugins/kopanowebmeetings/api/v1/config

```
failed to get KWM config - retrying 1
Error: Request failed with status code 500
(anonymous function) — kopanowebmeetings_7d1a87f48235bc84_bundle.js:207:74583
(anonymous function) — kopanowebmeetings_7d1a87f48235bc84_bundle.js:280:2957
(anonymous function) — kopanowebmeetings_7d1a87f48235bc84_bundle.js:207:73589
```

<img width="1440" alt="Screenshot 2019-12-11 at 20 25 46" src="https://user-images.githubusercontent.com/45794753/70653300-81e01b80-1c54-11ea-8d44-597bdd3ade40.png">

Is this a bug, or what are my misconceptions about this? :)

**Comment by socialSynergy** [comment]
Now we are also seeing this kind of error:

<img width="760" alt="Screenshot 2019-12-11 at 20 34 26" src="https://user-images.githubusercontent.com/45794753/70653948-b3a5b200-1c55-11ea-96ef-941543a7c538.png">

```
[Log] Loading kopanowebmeetings plugin (5.8f4edf63ea0d1d376f2f.js, line 1)
[Log] UserStatuses – {OFFLINE: "offline", AWAY: "away", ONLINE: "online", …} (kopanowebmeetings_7d1a87f48235bc84_bundle.js, line 290)
{OFFLINE: "offline", AWAY: "away", ONLINE: "online", DND: "dnd"}Object
[Log] Loaded kopanowebmeetings plugin (5.8f4edf63ea0d1d376f2f.js, line 1)
[Log] websocket connecting to wss://domain.com/api/v4/websocket (5.8f4edf63ea0d1d376f2f.js, line 1)
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (config, line 0)
[Warning] failed to get KWM config - retrying 1 – Error: Request failed with status code 500 (kopanowebmeetings_7d1a87f48235bc84_bundle.js, line 290)
Error: Request failed with status code 500
[Log] RootContainer.render (kopanowebmeetings_7d1a87f48235bc84_bundle.js, line 290)
[Error] TypeError: undefined is not an object (evaluating 't.teammate_id')
(anonymous function) — kopanowebmeetings_7d1a87f48235bc84_bundle.js:290:31171
(anonymous function) — wrapMapToProps.js:50
(anonymous function) — selectorFactory.js:20
run — connectAdvanced.js:21
(anonymous function) — connectAdvanced.js:180
Connect(t) — connectAdvanced.js:118
co — react-dom.production.min.js:133
Er — react-dom.production.min.js:167:343
Ui — react-dom.production.min.js:233:114
Gi — react-dom.production.min.js:234
Ts — react-dom.production.min.js:250:177
Rs — react-dom.production.min.js:248:390
gs — react-dom.production.min.js:246:202
$i — react-dom.production.min.js:243:250
enqueueSetState — react-dom.production.min.js:130:478
(anonymous function) — react.production.min.js:14
(anonymous function) — needs_team.jsx:185
promiseReactionJob

	ui (main.0335f158af23c706d592.js:36:75236)
	(anonymous function) (main.0335f158af23c706d592.js:36:80283)
	oi (main.0335f158af23c706d592.js:36:73072)
	ai (main.0335f158af23c706d592.js:36:72872)
	Hi (main.0335f158af23c706d592.js:36:82991)
	Yi (main.0335f158af23c706d592.js:36:85308)
	(anonymous function) (main.0335f158af23c706d592.js:36:98515)
	(anonymous function) (main.0335f158af23c706d592.js:45:3196)
	ks (main.0335f158af23c706d592.js:36:98472)
	Ts (main.0335f158af23c706d592.js:36:98226)
	Rs (main.0335f158af23c706d592.js:36:97571)
	gs (main.0335f158af23c706d592.js:36:96592)
	$i (main.0335f158af23c706d592.js:36:95466)
	enqueueSetState (main.0335f158af23c706d592.js:36:44993)
	(anonymous function) (main.0335f158af23c706d592.js:28:1920)
	(anonymous function) (5.8f4edf63ea0d1d376f2f.js:1:1408734)
	promiseReactionJob
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 't.teammate_id')
	Rs (main.0335f158af23c706d592.js:36:97776)
	gs (main.0335f158af23c706d592.js:36:96592)
	$i (main.0335f158af23c706d592.js:36:95466)
	enqueueSetState (main.0335f158af23c706d592.js:36:44993)
	(anonymous function) (main.0335f158af23c706d592.js:28:1920)
	(anonymous function) (5.8f4edf63ea0d1d376f2f.js:1:1408734)
	promiseReactionJob
```

**Comment by socialSynergy** [comment]
@fbartels Do you have maybe any ideas regarding this issue?

**Comment by fbartels** [comment]
Hi @tech348712013870132,

I have seen your issue yesterday morning, but did not yet have time to look into it. If you need priority handling I suggest to get directly in contact with our support: https://kopano.com/support-info/

**Comment by socialSynergy** [comment]
@fbartels Normal priority support should be sufficient for us at this point in time.
We are just in the evaluation phase with your products and would like to get them up and running for further testing.

I hope we hear back from you :)

**Comment by fbartels** [comment]
I have now started looking into this.

> Mattermost (v5.13.2) 

is there a particular reason for using this version? Mattermost has by now also released 5.17.1

**Comment by socialSynergy** [comment]
@fbartels The reason is that we have encountered a bug within the mattermost helm chart that makes it impossible for us to update it at the moment:

--> https://github.com/mattermost/mattermost-docker/issues/434

Is your plugin in general not compatible to this version of mattermost (v5.13.2)?

**Comment by fbartels** [comment]
> Is your plugin in general not compatible to this version of mattermost (v5.13.2)?

I would not expect so. the last time I tried it was with some 5.14 version. 

I had this comment already open for several days, so before it gets lost I decided to finally send it. Maybe I find some time to actually test today.

**Comment by socialSynergy** [comment]
@fbartels Thank you for your support! That would be very helpful for us.

And also a big thank you in general for your open-source efforts :)

**Comment by socialSynergy** [comment]
Update: We are now on the newest version 5.18.0 of mattermost.

Now we have a new error (browser console):

`TypeError: undefined is not an object (evaluating 't.teammate_id') — kopanowebmeetings_7d1a87f48235bc84_bundle.js:289`

and 

```
failed to get KWM config - retrying 3
Error: Request failed with status code 500
(anonymous function) — kopanowebmeetings_7d1a87f48235bc84_bundle.js:207:74583
(anonymous function) — kopanowebmeetings_7d1a87f48235bc84_bundle.js:280:2957
(anonymous function) — kopanowebmeetings_7d1a87f48235bc84_bundle.js:207:73589
```

@fbartels Any ideas about this?

**Comment by fbartels** [comment]
Hi @tech348712013870132,

I have done some tests on friday and wanted to first internally discuss things before updating here again. I think in the end the `Error: Request failed with status code 500` error is a configuration mistake in regards to kwmserver (it's probably not reachable from mattermost), but the dealbreaker looks to be the Javascript issue.

In past versions one could reload mattermost and then continue to use the plugin, but that does not seem to be the case with the newer releases, where Mattermost stops loading when the kwmplugin is enabled.

This plugin was for us a bit of a test case to experiment with WebRTC and we have since then moved on and released [Kopano Meet](https://meet-app.io/) which is a full featured video conferencing solution (one to one, group calls, screensharing).

The original idea was to add some sort of integration from Meet back to Mattermost, but since Mattermost hasn't really caught on by our customers this is unlikely to happen anytime soon. Until then you can still install Meet stand-alone and just share group links manually into Mattermost.

I have added a notice to the readme:
https://github.com/Kopano-dev/mattermost-plugin-kopanowebmeetings/commit/4802d55cb1c1184a65904d81b3d679befc66c2d3
