### ISSUE TITLE
v0.1.0-12 does not load

### ISSUE THREAD

**Issue by sraupach** [Kopano-dev/mattermost-plugin-kopanowebmeetings#2]
Hi,
i updated the Plugin fropm 1.0.10 to 1.0.12 but it does not load.

{"level":"debug","ts":1532435285.417535,"caller":"app/plugin.go:176","msg":"Activating plugin","plugin_id":"kopanowebmeetings"}
{"level":"error","ts":1532435285.424512,"caller":"app/plugin.go:158","msg":"Plugin failed to activate","plugin_id":"kopanowebmeetings","err":"unable to read webapp bundle: kopanowebmeetings: open plugins/kopanowebmeetings/static/kopanowebmeetings_bundle-b25ef3ea.js: no such file or directory"}

The file does exsist but not in that path. is that a known issue?

thanks in advance

**Comment by fbartels** [comment]
Hi @sraupach ,

Weird earlier today it was working for me. 

> The file does exsist but not in that path. is that a known issue?

The archive for upload in Mattermost is created in  https://github.com/Kopano-dev/mattermost-plugin-kopanowebmeetings/blob/master/Makefile#L126-L140 maybe you want to propose a fix in a PR? 

Ps: the version is really 0.1.0-12

**Comment by sraupach** [comment]
Hi @fbartels,

tbh i am not that experienced with github and does not see were to actually fix it.
hmm i am not quite sure if the problem has its origin in creating the archive because its trying to open that .js file which is in kopanowebmeetings/webapp. The static folder has just a mp3..i guess the ring sound? (even in version 0.1.0-11)

**Comment by fbartels** [comment]
Hi, 

meanwhile I was able to reproduce it as well. We decided to revert the last change and tag a new release. you will see a 0.2.0 relatively soon. this will restore the call button, but still suffers from the overlaying. We had some confusion here and I thought it was fixed, but the issue is actually still open.

**Comment by longsleep** [comment]
This is resolved, though since we were unable to avoid caching issues on the plugin side of things make sure to clear the clients cache after updating the plugin.

Mattermost seems to want to fix this for 5.2 - see https://mattermost.atlassian.net/browse/MM-11420 for reference.
