### ISSUE TITLE
Can't start WebMeeting

### ISSUE THREAD

**Issue by drJeckyll** [Kopano-dev/mattermost-plugin-kopanowebmeetings#4]
I have problem starting WebMeeting in mattermost (Version: 5.6.0 Build Number: 5.6.0_rc2).
In Firefox (66.0a1 (2018-12-12), when I click button with a camera I'm asked to give permission for my cam/mic to b used which is normal. Then camera start working, but there is no any indication in mattermost that meeting is started. In console I see this error:

![kopano_ff_start](https://user-images.githubusercontent.com/542513/49914534-4f151300-fe9a-11e8-8bae-8ee4c3f106de.png)

It's similar in Chrome (Version 71.0.3578.80 (Official Build) (64-bit)). Camera start working, but there is no indication in mattermost that something happened and this error is shown in console:

![kopano_chrome_start](https://user-images.githubusercontent.com/542513/49914616-adda8c80-fe9a-11e8-972e-a3eb55fa39ab.png)

In both browsers when plugin is activated mattermost don't load every time. I have to refresh couple of times, before I can see mattermost interface. Otherwise all I can see is a blank page with these errors in console:
Firefox:
![kopano_ff_console](https://user-images.githubusercontent.com/542513/49914674-e67a6600-fe9a-11e8-8820-ed443957950d.png)

Chrome:
![kpano_chrome_console](https://user-images.githubusercontent.com/542513/49914713-0c076f80-fe9b-11e8-8b62-967329ef5200.png)

All this is for kopano plugin 0.3 and kopano-kwmserver 0.13.1 running on Gentoo Linux. 

In plugin configuration I have only "Kopano Web Meetings Server URL", "http://192.168.1.110:8778" and "STUN server URI" which point to: stun:stun01.sipphone.com, but I try with stun.l.google.com:19302 with same results. I don't configure "TURN server URI" and have default "TURN user name" pointing to "mattermost-kwm-user" with "TURN shared secret" empty. I'm not sure if all these values are required, because in docs it say optional ... but ... may be I'm not doing something right.

**Comment by fbartels** [comment]
Hi @drJeckyll ,

thanks for your report. Mattermost 5.6 is not yet officially released, can you for good measure see if you have the same issue with 5.5.0? For 5.5.0 I am not able to observe the same error messages.

**Comment by drJeckyll** [comment]
Exactly the same with 5.5.1 and 5.5.0 - just checked again

**Comment by fbartels** [comment]
Hi @drJeckyll ,

I just upgraded my testing system to Mattermost 5.6.0, along with the mattermost plugin 0.3 and kwmserver 0.13.1 and am sadly not able to reproduce the issue. 

edit to clarify: I am speaking about the javascript errors you initially mentioned. the blank page that requires a reload when e.g. coming from the mattermost system console is a known issue.

**Comment by drJeckyll** [comment]
Who knows. I compiled plugin from source, but same issue occurred. 

I'm still not sure if everything is correctly configured from my side.

**Comment by fbartels** [comment]
There is not that much to configure. This is what I have stored as settings:
![image](https://user-images.githubusercontent.com/1257835/50084746-4dc84b00-01f8-11e9-82c7-0f9d80b15031.png)

My test environment is in Docker and I simply start kwmserver the following way:
```
echo "=> Start Kopano Web Meetings server"
KOPANO_KWMSERVERD_ADMIN_TOKENS_KEY=/etc/mattermost/kwm-admin-tokens.key
if [ ! -f "$KOPANO_KWMSERVERD_ADMIN_TOKENS_KEY" ]; then
        openssl rand -out "$KOPANO_KWMSERVERD_ADMIN_TOKENS_KEY" 32
fi
cd /opt/kopano-kwmserver/
./kwmserverd serve \
        --listen=0.0.0.0:8778 \
        --admin-tokens-key="$KOPANO_KWMSERVERD_ADMIN_TOKENS_KEY" &

```

**Comment by fbartels** [comment]
This plugin is now discontinued. We recommend to use [Kopano Meet](https://meet-app.io/) instead (which currently has no integration with Mattermost, though).
